# Generated by Django 3.1.5 on 2021-02-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(null=True, verbose_name='abstract'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='n_citation',
            field=models.IntegerField(null=True, verbose_name='citation'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='references',
            field=models.TextField(null=True, verbose_name='references'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='year',
            field=models.DateTimeField(null=True, verbose_name='time'),
        ),
    ]
