# Generated by Django 3.1.5 on 2021-02-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0002_auto_20210206_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='paper_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='publication_venue',
            new_name='venue',
        ),
    ]
