# Generated by Django 3.1.5 on 2021-02-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0004_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(null=True, to='paper.Author', verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='references',
            field=models.JSONField(null=True, verbose_name='references'),
        ),
    ]
