# Generated by Django 3.1.6 on 2021-03-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('paper', '0009_auto_20210306_1657'),
    ]
    operations = [
        migrations.AlterField(
            model_name='wordposition',
            name='word_name',
            field=models.CharField(max_length=512, verbose_name='word_name'),
        ),

    ]
