# Generated by Django 3.1.6 on 2021-03-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0011_auto_20210307_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querysearch',
            name='word',
            field=models.CharField(max_length=512, unique=True, verbose_name='word'),
        ),

    ]
