# Generated by Django 3.1.6 on 2021-03-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0012_auto_20210314_1137'),
    ]

    operations = [


        migrations.RemoveField(
            model_name='querysearch',
            name='papers',
        ),

        migrations.AddField(
            model_name='querysearch',
            name='words',
            field=models.JSONField(default=[], verbose_name='res_words'),
            preserve_default=False,
        )
    ]
